#!/bin/zsh
set -euo pipefail

SCRIPT_PATH="${0:A}"
ROOT_DIR="$(cd "$(dirname "$SCRIPT_PATH")/.." && pwd)"
COMMAND_NAME="${0:t}"
CONFIG_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/cilicili/sign-install-ipa.conf"
KEYCHAIN="${KEYCHAIN:-$HOME/Library/Keychains/login.keychain-db}"
SAVE_CONFIG=0
FORCE_CONFIGURE=0
IPA_PATH=""
PROFILE_PATH=""
P12_PATH=""
IDENTITY_NAME=""
DEVICE=""

usage() {
  cat <<EOF
Usage:
  $COMMAND_NAME [options] [unsigned.ipa]

Options:
  -c, --configure        Pick profile, optional p12, identity, and device; save them
      --save             Save options passed on this run
      --profile PATH     Provisioning profile (.mobileprovision)
      --p12 PATH         Optional signing certificate/private key (.p12) to import
      --identity NAME    Codesigning identity name or hash
      --device ID        devicectl device id, UDID, serial, or device name
      --config PATH      Config file path
  -h, --help             Show this help

Saved config:
  ~/.config/cilicili/sign-install-ipa.conf

The p12 password is requested when importing and is not written to config.
EOF
}

die() {
  echo "error: $*" >&2
  exit 1
}

require_file() {
  local path="$1"
  [[ -f "$path" ]] || die "missing file: $path"
}

shell_quote() {
  printf "%q" "$1"
}

read_path() {
  local prompt="$1"
  local default_path="$2"
  local required="$3"
  local value=""

  while true; do
    if [[ -n "$default_path" ]]; then
      read -r "value?$prompt [$default_path]: "
      value="${value:-$default_path}"
    else
      read -r "value?$prompt: "
    fi

    if [[ "$value" == "-" && "$required" == "optional" ]]; then
      print -r -- ""
      return
    fi

    if [[ -z "$value" && "$required" == "optional" ]]; then
      print -r -- ""
      return
    fi

    [[ -f "$value" ]] && {
      print -r -- "$value"
      return
    }

    echo "File not found: $value" >&2
  done
}

latest_unsigned_ipa() {
  find "$ROOT_DIR/build/debug-unsigned-ipa" -type f -name '*.ipa' -print 2>/dev/null | sort | tail -1
}

decode_profile() {
  local profile="$1"
  local plist="$2"
  security cms -D -i "$profile" > "$plist"
}

profile_value() {
  local plist="$1"
  local key="$2"
  plutil -extract "$key" raw -o - "$plist" 2>/dev/null || true
}

identity_is_valid() {
  local identity="$1"
  security find-identity -v -p codesigning "$KEYCHAIN" 2>/dev/null | grep -Fq "$identity"
}

import_p12() {
  local p12="$1"
  [[ -n "$p12" ]] || return
  require_file "$p12"

  local password=""
  read -rs "password?P12 password for $(basename "$p12") (empty if none): "
  print
  security import "$p12" \
    -k "$KEYCHAIN" \
    -P "$password" \
    -T /usr/bin/codesign \
    -T /usr/bin/security \
    -f pkcs12 >/dev/null
}

choose_identity() {
  local raw=""
  raw="$(security find-identity -v -p codesigning "$KEYCHAIN" 2>/dev/null | sed -n 's/^[[:space:]]*[0-9]*) [[:xdigit:]]\{40\} "\(.*\)"$/\1/p')"
  local -a identities
  identities=("${(@f)raw}")

  if (( ${#identities[@]} == 0 )); then
    local manual=""
    read -r "manual?Signing identity name/hash: "
    print -r -- "$manual"
    return
  fi

  echo "Signing identities:" >&2
  local i
  for i in {1..${#identities[@]}}; do
    echo "  $i) $identities[$i]" >&2
  done

  local choice=""
  while true; do
    read -r "choice?Choose signing identity [1]: "
    choice="${choice:-1}"
    if [[ "$choice" == <-> ]] && (( choice >= 1 && choice <= ${#identities[@]} )); then
      print -r -- "$identities[$choice]"
      return
    fi
    echo "Invalid choice: $choice" >&2
  done
}

save_config() {
  mkdir -p "$(dirname "$CONFIG_PATH")"
  chmod 700 "$(dirname "$CONFIG_PATH")"
  {
    echo "# Generated by Scripts/sign-install-unsigned-ipa.sh"
    echo "SII_PROFILE_PATH=$(shell_quote "$PROFILE_PATH")"
    echo "SII_P12_PATH=$(shell_quote "$P12_PATH")"
    echo "SII_IDENTITY_NAME=$(shell_quote "$IDENTITY_NAME")"
    echo "SII_DEVICE=$(shell_quote "$DEVICE")"
  } > "$CONFIG_PATH"
  chmod 600 "$CONFIG_PATH"
  echo "Saved config: $CONFIG_PATH"
}

configure() {
  local default_profile="/Users/rayc/Desktop/Apple Distribution Eric Kirsche KQ737H7L22_certificate/cert.mobileprovision"
  [[ -f "$default_profile" ]] || default_profile=""
  PROFILE_PATH="$(read_path "Provisioning profile path" "${PROFILE_PATH:-$default_profile}" required)"

  local profile_plist
  profile_plist="$(mktemp /tmp/sign-install-profile.XXXXXX)"
  decode_profile "$PROFILE_PATH" "$profile_plist"

  local default_p12="/Users/rayc/Desktop/Apple Distribution Eric Kirsche KQ737H7L22_certificate/cert.p12"
  [[ -f "$default_p12" ]] || default_p12=""
  P12_PATH="$(read_path "P12 path, press return for default, type - to skip" "${P12_PATH:-$default_p12}" optional)"
  if [[ -n "$P12_PATH" ]]; then
    import_p12 "$P12_PATH"
  fi

  IDENTITY_NAME="$(choose_identity)"

  local default_device
  default_device="$(profile_value "$profile_plist" ProvisionedDevices.0)"
  echo "Available devices:"
  xcrun devicectl list devices || true
  read -r "DEVICE?Device id/name/UDID [$default_device]: "
  DEVICE="${DEVICE:-$default_device}"

  [[ -n "$DEVICE" ]] || die "no device selected"
  save_config
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -c|--configure)
        FORCE_CONFIGURE=1
        ;;
      --save)
        SAVE_CONFIG=1
        ;;
      --profile)
        shift
        PROFILE_PATH="${1:-}"
        ;;
      --p12)
        shift
        P12_PATH="${1:-}"
        ;;
      --identity)
        shift
        IDENTITY_NAME="${1:-}"
        ;;
      --device)
        shift
        DEVICE="${1:-}"
        ;;
      --config)
        shift
        CONFIG_PATH="${1:-}"
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      -*)
        die "unknown option: $1"
        ;;
      *)
        [[ -z "$IPA_PATH" ]] || die "only one IPA path is supported"
        IPA_PATH="$1"
        ;;
    esac
    shift
  done
}

load_config() {
  [[ -f "$CONFIG_PATH" ]] || return 0
  source "$CONFIG_PATH"
  PROFILE_PATH="${PROFILE_PATH:-${SII_PROFILE_PATH:-}}"
  P12_PATH="${P12_PATH:-${SII_P12_PATH:-}}"
  IDENTITY_NAME="${IDENTITY_NAME:-${SII_IDENTITY_NAME:-}}"
  DEVICE="${DEVICE:-${SII_DEVICE:-}}"
}

select_ipa_if_needed() {
  [[ -n "$IPA_PATH" ]] && return
  local default_ipa
  default_ipa="$(latest_unsigned_ipa)"
  IPA_PATH="$(read_path "Unsigned IPA path" "$default_ipa" required)"
}

install_profile() {
  local profile="$1"
  local plist="$2"
  local uuid
  uuid="$(profile_value "$plist" UUID)"
  [[ -n "$uuid" ]] || die "profile has no UUID: $profile"
  mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
  cp "$profile" "$HOME/Library/MobileDevice/Provisioning Profiles/$uuid.mobileprovision"
}

target_bundle_id() {
  local profile_bundle="$1"
  local original_bundle="$2"

  if [[ "$profile_bundle" == *"*"* ]]; then
    local prefix="${profile_bundle%%\**}"
    local suffix="${profile_bundle#*\*}"
    [[ "$original_bundle" == "$prefix"* && "$original_bundle" == *"$suffix" ]] || \
      die "app bundle id '$original_bundle' does not match profile wildcard '$profile_bundle'"
    print -r -- "$original_bundle"
  else
    print -r -- "$profile_bundle"
  fi
}

sign_and_install() {
  require_file "$IPA_PATH"
  require_file "$PROFILE_PATH"
  [[ -n "$IDENTITY_NAME" ]] || die "missing signing identity; run with --configure"
  [[ -n "$DEVICE" ]] || die "missing device; run with --configure"

  if ! identity_is_valid "$IDENTITY_NAME"; then
    [[ -n "$P12_PATH" ]] || die "identity not found in keychain: $IDENTITY_NAME"
    echo "Identity not found; importing p12..."
    import_p12 "$P12_PATH"
  fi
  identity_is_valid "$IDENTITY_NAME" || die "identity is still not valid: $IDENTITY_NAME"

  local ipa_name out_dir extract_dir app profile_plist entitlements app_identifier team_id profile_bundle original_bundle bundle_id
  ipa_name="$(basename "$IPA_PATH" .ipa)"
  out_dir="$ROOT_DIR/build/debug-resigned-install/$ipa_name"
  extract_dir="$out_dir/extracted"
  app=""
  profile_plist="$out_dir/profile.plist"
  entitlements="$out_dir/entitlements.plist"

  rm -rf "$out_dir"
  mkdir -p "$extract_dir"
  ditto -x -k "$IPA_PATH" "$extract_dir"

  local extracted_app
  extracted_app="$(find "$extract_dir/Payload" -maxdepth 1 -type d -name '*.app' -print | sed -n '1p')"
  [[ -n "$extracted_app" ]] || die "IPA has no Payload/*.app"
  app="$out_dir/$(basename "$extracted_app")"
  ditto "$extracted_app" "$app"

  zsh "$ROOT_DIR/Scripts/remove-empty-frameworks.sh" "$app"

  decode_profile "$PROFILE_PATH" "$profile_plist"
  install_profile "$PROFILE_PATH" "$profile_plist"
  plutil -extract Entitlements xml1 -o "$entitlements" "$profile_plist"

  app_identifier="$(profile_value "$profile_plist" Entitlements.application-identifier)"
  team_id="$(profile_value "$profile_plist" TeamIdentifier.0)"
  profile_bundle="${app_identifier#*.}"
  original_bundle="$(plutil -extract CFBundleIdentifier raw -o - "$app/Info.plist")"
  bundle_id="$(target_bundle_id "$profile_bundle" "$original_bundle")"

  plutil -replace CFBundleIdentifier -string "$bundle_id" "$app/Info.plist"
  cp "$PROFILE_PATH" "$app/embedded.mobileprovision"

  if [[ "$profile_bundle" == *"*"* ]]; then
    plutil -replace application-identifier -string "$team_id.$bundle_id" "$entitlements"
  fi

  find "$app" -type d \( -name '*.framework' -o -name '*.appex' -o -name '*.app' \) -not -path "$app" | while IFS= read -r nested; do
    codesign --force --sign "$IDENTITY_NAME" --timestamp=none "$nested"
  done

  find "$app" -type f \( -name '*.dylib' -o -perm +111 \) -path '*/Frameworks/*' | while IFS= read -r binary; do
    if file "$binary" | grep -q 'Mach-O'; then
      codesign --force --sign "$IDENTITY_NAME" --timestamp=none "$binary" || true
    fi
  done

  codesign --force --sign "$IDENTITY_NAME" --entitlements "$entitlements" --timestamp=none "$app"
  codesign --verify --deep --strict --verbose=2 "$app"

  echo "Installing $bundle_id to $DEVICE..."
  xcrun devicectl device install app --device "$DEVICE" "$app" --timeout 180
  echo "Signed app: $app"
}

parse_args "$@"
load_config

if (( FORCE_CONFIGURE )) || [[ -z "$PROFILE_PATH" || -z "$IDENTITY_NAME" || -z "$DEVICE" ]]; then
  configure
elif (( SAVE_CONFIG )); then
  save_config
fi

select_ipa_if_needed
sign_and_install
